sprint project 9
VladimirKomov/java-filmorate pull request #1
Opened 2022-10-14 08:22 UTC by VladimirKomov

2022-10-14 08:37 UTC, VladimirKomov commented
Добавлен функционал спринта 9

2022-10-15 09:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Получен запрос PUT /films.");
Put возвращает 500
{
	"timestamp": "2022-10-15T08:58:17.354+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}
ru.yandex.practicum.filmorate.exception.AlreadyExistException: Фильм уже добавлен
Да он уже существует, но PUT это для обновления, т.е. сущность должна обновиться.

2022-10-15 09:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
А как удалить фильм? Добавь, пожалуйста, контроллер на удаление сущностей

2022-10-15 09:12 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsValue(user)) {
PUT создается для обновления контента. Если пользователь уже существует, то его стоит обновить

2022-10-15 09:22 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.entrySet()
На мой взгляд написано сложно. Можно написать return new ArrayList<>(films.values());
Если считаешь, что твой вариант красивее, оставь его. Это комментарий из разряда "обсудить"

2022-10-15 09:25 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    void filmGood() {
Тут явно не хватает параметризованных тестов, которые могли бы убрать дублирование. https://www.baeldung.com/parameterized-tests-junit-5

2022-10-15 09:25 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Совсем немного замечаний

2022-10-15 16:09 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Получен запрос PUT /films.");
готово

2022-10-15 16:09 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
готово

2022-10-15 16:09 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsValue(user)) {
готово

2022-10-15 16:09 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.entrySet()
готово

2022-10-17 09:12 UTC, VladimirKomov commented
Реализовал по замечаниям. Кроме post запроса при создании пользователя с таким же e-mail, при тестировании на github просит статус 500

2022-10-17 10:23 UTC, VladimirKomov commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    void filmGood() {
готово

2022-10-18 17:02 UTC, EvgenyKoptubenko approved these changes
Замечания исправлены. Работа сделана хорошо. Спасибо.

2022-10-24 06:50 UTC, merged