Add database
VladimirKomov/java-filmorate pull request #3
Opened 2022-11-24 09:07 UTC by VladimirKomov

2022-11-24 19:28 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        //тут хуета
Точно? Есть предложения как улучшить?

2022-11-24 19:39 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Удаляется Пользователь id={}", id);
В логе написано, что пользователь удаляется, но метод Get.
Если попробовать удалить пользователя http://localhost:8080/users/2222
То будет 500
{
	"error": "500 INTERNAL_SERVER_ERROR {}",
	"description": "Request method 'DELETE' not supported"
}
Но должно быть 405 - Method Not Allowed

2022-11-24 21:10 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      //получение списка всех пользователей
Если добавить пользователя несколько раз, то падает. Все-таки лучше пользователю сообщить, что такой пользователь уже существует
{
	"error": "500 INTERNAL_SERVER_ERROR {}",
	"description": "PreparedStatementCallback; Unique index or primary key violation: \"PUBLIC.CONSTRAINT_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email3@email.com' )\"; SQL statement:\ninsert into users (email, login, name, birthday) values (?, ?, ?, ?) [23505-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PUBLIC.CONSTRAINT_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email3@email.com' )\"; SQL statement:\ninsert into users (email, login, name, birthday) values (?, ?, ?, ?) [23505-214]"
}

Если отправить неверные данные, то тоже присылается некрасивое сообщение об ошибке
{
	"error": "500 INTERNAL_SERVER_ERROR {}",
	"description": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controller.UserController.post(ru.yandex.practicum.filmorate.model.User): [Field error in object 'user' on field 'email': rejected value [email3email.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@9adf5b4,.*]; default message [must be a well-formed email address]] "
}

2022-11-24 21:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public void addLike(@PathVariable long id, @PathVariable long userId) {
http://localhost:8080/films/1/like/aaa
{
	"error": "500 INTERNAL_SERVER_ERROR {}",
	"description": "Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: \"aaa\""
}

2022-11-24 21:12 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Совсем немного замечаний

2022-11-25 05:54 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        //тут хуета
Это для себя оставлял, для мотивации. Буду выбрить формулировки помягче.

2022-11-25 06:14 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Удаляется Пользователь id={}", id);
Лог исправлен, добавлена обработка исключения HttpRequestMethodNotSupportedException

2022-11-25 06:56 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public void addLike(@PathVariable long id, @PathVariable long userId) {
Добавлена обработка TypeMismatchException

2022-11-25 09:15 UTC, VladimirKomov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      //получение списка всех пользователей
Добавлена обработка исключений.

2022-11-25 18:32 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2022-11-25 18:38 UTC, merged